// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CoucouController from "./coucou_controller"
application.register("coucou", CoucouController)

import CounterController from "./counter_controller"
application.register("counter", CounterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IndexController from "./index_controller"
application.register("index", IndexController)
